/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppSettingIndex: typeof import('./src/components/appSetting/appSettingIndex.vue')['default']
    ChatWindowIndex: typeof import('./src/components/chatWindow/chatWindowIndex.vue')['default']
    ComentQuoteIndex: typeof import('./src/components/comentQuote/comentQuoteIndex.vue')['default']
    EditMd: typeof import('./src/components/mobileSetting/components/editMd.vue')['default']
    EditNick: typeof import('./src/components/mobileSetting/components/editNick.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FriendsListIndex: typeof import('./src/components/friendsList/friendsListIndex.vue')['default']
    MoIndex: typeof import('./src/components/mobileSetting/moIndex.vue')['default']
    MoreIndex: typeof import('./src/components/mobileMore/moreIndex.vue')['default']
    RichTextIndex: typeof import('./src/components/sendFoot/component/richText/richTextIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTextIndex: typeof import('./src/components/searchText/searchTextIndex.vue')['default']
    SendFileIndex: typeof import('./src/components/sendFile/sendFileIndex.vue')['default']
    SendFootIndex: typeof import('./src/components/sendFoot/sendFootIndex.vue')['default']
    SendMediaIndex: typeof import('./src/components/sendMedia/sendMediaIndex.vue')['default']
    TipsMessagesIndex: typeof import('./src/components/tipsMessages/tipsMessagesIndex.vue')['default']
    VideoCallAnwsererIndex: typeof import('./src/components/videoCallAnwserer/videoCallAnwsererIndex.vue')['default']
    VideoCallOffererIndex: typeof import('./src/components/VideoCallOfferer/videoCallOffererIndex.vue')['default']
  }
}
