/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppSetting: typeof import('./src/components/appSetting.vue')['default']
    ChatWindow: typeof import('./src/components/chatWindow.vue')['default']
    ComentQuote: typeof import('./src/components/comentQuote.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FriendsList: typeof import('./src/components/friendsList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendFile: typeof import('./src/components/sendFile.vue')['default']
    SendFootIndex: typeof import('./src/components/sendFoot/sendFootIndex.vue')['default']
    SendMedia: typeof import('./src/components/sendMedia.vue')['default']
    TipsMessages: typeof import('./src/components/tipsMessages.vue')['default']
    VideoCallAnwserer: typeof import('./src/components/videoCallAnwserer.vue')['default']
    VideoCallOfferer: typeof import('./src/components/videoCallOfferer.vue')['default']
  }
}
